# Generated by Django 3.1.13 on 2021-12-28 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0002_auto_20211227_1354"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="customers",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cars.customer",
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="owners",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="cars.owner"
            ),
        ),
    ]
