# Generated by Django 3.1.13 on 2021-12-28 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0007_auto_20211228_0248"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car",
            name="car_rental",
        ),
        migrations.AddField(
            model_name="carrental",
            name="car",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="cars.car"
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cars.owner",
            ),
        ),
        migrations.AlterField(
            model_name="carrental",
            name="code",
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name="carrental",
            name="customer",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cars.customer",
            ),
        ),
    ]
