# Generated by Django 3.1.13 on 2021-12-28 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0008_auto_20211228_0305"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cars",
                to="cars.owner",
            ),
        ),
    ]
