# Generated by Django 3.1.13 on 2021-12-28 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_auto_20211228_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrental',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.customer'),
        ),
    ]
